<!DOCTYPE html>
<html lang="en">

<head>
    <title>Admin - Étel típusok</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Great+Vibes" rel="stylesheet">

    <link rel="stylesheet" href="/css/open-iconic-bootstrap.min.css">

    <link rel="stylesheet" href="/css/owl.carousel.min.css">
    <link rel="stylesheet" href="/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="/css/magnific-popup.css">
    <link rel="stylesheet" href="/css/animate.css">


    <link rel="stylesheet" href="/css/aos.css">

    <link rel="stylesheet" href="/css/ionicons.min.css">

    <link rel="stylesheet" href="/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="/css/jquery.timepicker.css">


    <link rel="stylesheet" href="/css/flaticon.css">
    <link rel="stylesheet" href="/css/icomoon.css">
    <link rel="stylesheet" href="/css/style.css">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
        <div class="container">
            <a class="navbar-brand" href="/admin/uj-etel-tipus">Admin - Étel típusok
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
                aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="oi oi-menu"></span> Menu
            </button>
            <div class="collapse navbar-collapse" id="ftco-nav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item"><a href="/admin/uj-etel" class="nav-link">Ételek</a></li>
                    <li class="nav-item"><a href="/" class="nav-link">Home</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- END nav -->
    <section class="ftco-section">
        <div class="container">
            <div class="row">
                <div class="col-md-6 mb-5 pb-3">
                    <h3><?= isset($query['id'])?'Módosítás': 'Új típus'?></h3>
                    <form <?= isset($query['id'])?'action="/dishTypes/edit?id='.$query['id'].'"':'action="/dishTypes"'?> method="POST">
                        <div class="form-group row">
                            <label for="inputName" class="col-sm-2 col-form-label">Név</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="inputName" name="name" value="<?= isset($query['id'])?$dishType['name']: ''?>" required>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="exampleFormControlTextarea1" class="col-sm-2 col-form-label">Leírás</label>
                            <div class="col-sm-10">
                                <textarea class="form-control" id="exampleFormControlTextarea1" name="description" rows="3" required><?= isset($query['id'])?$dishType['description']: ''?></textarea>
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-sm-10">
                                <button type="submit" class="btn btn-primary">Elküldés</button>
                            </div>
                        </div>
                    </form>
                </div>

                <div class="col-md-6" style="height: calc(100vh - 265px); overflow-y: scroll;">
                    <?php foreach($dishTypes as $dishType): ?>
                    <div class="row mb-4">
                        <div class="d-flex">
                            <div class="desc pl-3">
                                <div class="d-flex text align-items-center">
                                    <h3><span><?= $dishType['name'] ?></span></h3>
                                </div>
                                <div class="d-block">
                                    <p><?= $dishType['description'] ?></p>
                                </div>
                                <a class="float-left" href="/admin/etel-tipusok?id=<?= $dishType['id'] ?>">
                                    <button class="btn btn-sm btn-outline-warning float-left mr-1">Szerkesztés</button>
                                </a>
                                <form class="float-left" action="/dishTypes/delete?id=<?= $dishType['id'] ?>" method="POST">
                                    <button type="submit"
                                        class="btn btn-sm btn-outline-danger">Törlés</button>
                                </form>
                            </div>
                        </div>
                    </div>
                    <?php endforeach; ?>
                </div>
            </div>
    </section>


    <!-- loader -->
    <div id="ftco-loader" class="show fullscreen">
        <svg class="circular" width="48px" height="48px">
            <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" />
            <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00" />
        </svg>
    </div>


    <script src="/js/jquery.min.js"></script>
    <script src="/js/jquery-migrate-3.0.1.min.js"></script>
    <script src="/js/popper.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/jquery.easing.1.3.js"></script>
    <script src="/js/jquery.waypoints.min.js"></script>
    <script src="/js/jquery.stellar.min.js"></script>
    <script src="/js/owl.carousel.min.js"></script>
    <script src="/js/jquery.magnific-popup.min.js"></script>
    <script src="/js/aos.js"></script>
    <script src="/js/jquery.animateNumber.min.js"></script>
    <script src="/js/bootstrap-datepicker.js"></script>
    <script src="/js/jquery.timepicker.min.js"></script>
    <script src="/js/scrollax.min.js"></script>
    <script src="/js/main.js"></script>

</body>

</html>